name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android cmdline-tools & SDK packages
        shell: bash
        run: |
          set -e
          # 環境変数をジョブ全体に永続化
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk"      >> $GITHUB_ENV

          export ANDROID_SDK_ROOT="$HOME/android-sdk"
          export ANDROID_HOME="$ANDROID_SDK_ROOT"

          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT"

          # cmdline-tools 取得＆配置
          curl -fsSLo cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdline-tools.zip -d cmdline-tools
          if [ -d cmdline-tools/cmdline-tools/bin ]; then
            src="cmdline-tools/cmdline-tools"
          else
            src="cmdline-tools"
          fi
          mkdir -p cmdline-tools/latest
          mv "$src"/* cmdline-tools/latest/ || true
          rm -rf cmdline-tools/cmdline-tools cmdline-tools.zip || true

          # PATH 追加（次ステップでも有効）
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools"           >> $GITHUB_PATH

          SDKM="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"

          # ★ ここは時々 Broken pipe で1を返すので “無視” するのがコツ
          yes | "$SDKM" --sdk_root="$ANDROID_SDK_ROOT" --licenses || true

          # 必須パッケージをインストール（失敗時は止める）
          yes | "$SDKM" --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-33" "build-tools;33.0.2"

          # 確認（ログ用）
          ls -l "$ANDROID_SDK_ROOT/platforms/android-33"/android.jar
          ls -l "$ANDROID_SDK_ROOT/build-tools/33.0.2"/aapt2

      # Gradleラッパー無しで公式アクションに実行させる
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: :app:assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
